name: "RSpec"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    env:
      api-dir: ./

    strategy:
      fail-fast: false
      matrix:
        versions: [ '3.2', '3.3', '3.4' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Ruby ${{ matrix.versions }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.versions }}
        bundler-cache: true

    - name: RSpec spec (Ruby ${{ matrix.versions }})
      working-directory: ${{env.api-dir}}
      run: bundle exec rspec spec --format progress
